paths changed

diff --git a/.github/workflows/action_on_request.yml b/.github/workflows/action_on_request.yml
--- a/.github/workflows/action_on_request.yml
+++ b/.github/workflows/action_on_request.yml
@@ -34,12 +34,27 @@ jobs:
       uses: actions/checkout@v2
       with:
         fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
-    - name: Install tox and any other packages
-      run: pip install tox
-    - name: Run tox
-      run: tox -e py
-    - name: SonarCloud Scan
-      uses: SonarSource/sonarcloud-github-action@master
+        
+    - name: Test with pytest
+      run: |
+        coverage run --branch --source=bom_analysis -m pytest -v tests || true
+        coverage xml -o coverage.xml
+        cp coverage.xml .coverage-reports/test-coverage-pytest.xml
+        pytest -v -o junit_family=xunit1 --junitxml=.coverage-reports/test-results.xml tests
+    - name: Upload pytest test results
+      uses: actions/upload-artifact@v3
+      with:
+        name: pytest-results
+        path: .coverage-reports/test-results.xml
+      # Use always() to always run this step to publish test results when there are test failures
+      if: ${{ always() }}
+    - name: Upload coverage
+      uses: actions/upload-artifact@v3
+      with:
+        name: test-coverage
+        path: .coverage-reports/test-coverage-pytest.xml
+      # Use always() to always run this step to publish test results when there are test failures
+      if: ${{ always() }}  
     - name: Test documentation build
       run: |
         sphinx-apidoc -f -o docs/source/ bom_analysis/
